### ISSUE TITLE
How to deal with paired-end sequencing file

### ISSUE THREAD

**Issue by rongfengchen** [medvir/SmaltAlign#12]
For Illumina sequencing, we have R1 and R2 fastq files for one sample? How to deal with these paired-end sequencing file? Should I merge R1 and R2 first, then use SmaltAlign to do align?

**Comment by MaryamZaheri** [comment]
If the paired-end reads overlap you can use tools such as [PEAR](https://cme.h-its.org/exelixis/web/software/pear/) to merge the reads. Otherwise you can just concat all reads in one file and use the tool.
