### ISSUE TITLE
lofreq doesn't run if amount of cores is below 10

### ISSUE THREAD

**Issue by sschmutz** [medvir/SmaltAlign#2]
https://github.com/medvir/SmaltAlign/blob/f4308706dc3c53bffeafb1ccffde941e8e6ab498/smaltalign.sh#L118

in this line, lofreq calls variants in parallel (`--pp-threads 10`). Now if you run smaltalign.sh on a computer with less than 10 cores there'll be no lofreq.vcf file.
To check the amount of cores:
linux: `nproc`
mac os: `sysctl -n hw.ncpu `

**Comment by mihuber** [comment]
should we add something like this:
`cores=$(nproc)`  
`cores=$(expr $cores - 2)  ### don't use all cores  `
`lofreq call-parallel --pp-threads $cores -f $ref -o ${name}_${it}_lofreq.vcf ${name}_${it}.bam`  
How does one distinguish if linux or mac os?

**Comment by mihuber** [comment]
`if [ "$(uname)" == "Darwin" ]; then`
`    cores=$(sysctl -n hw.ncpu) # Mac OS X platform`        
`elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then`
`    cores=$(nproc) # GNU/Linux platform`
`fi`
`cores=$(expr $cores / 2) ### only run on half the cores`
`lofreq call-parallel --pp-threads $cores -f $ref -o ${name}_${it}_lofreq.vcf ${name}_${it}.bam`

**Comment by mihuber** [comment]
fixed
