### ISSUE TITLE
wts.R and cov_plot.R hashbang, location of Rscript

### ISSUE THREAD

**Issue by mihuber** [medvir/SmaltAlign#5]
The scripts wts.R and cov_plot.R are not working for me (and users other than @sschmutz) with `#!/home/schmutz.stefan/miniconda3/envs/SmaltAlign/bin/Rscript` hashbang.

**Comment by sschmutz** [comment]
It's working in conda's base environment `conda activate base` and then `Rscript wts.R or cov_plot.R <file directory>`.

There was a version conflict of the R package seqinr and another tool.
I can try again and include all necessary packages in the SmaltAlign `environment.yml` document.

Having the right version of the tools is critical with SmaltAlign. If you install the newest versions of all dependencies, it doesn't work.

**Comment by mihuber** [comment]
No, I think the problem is that it looks for Rscript in your home, which I don't have access.

> (base) mihuber@timavo:/analyses/Diagnostics/virome/190204_1000428184$ ../../Repositories/SmaltAlign/cov_plot.R ../190204_1000428184/
> -bash: ../../Repositories/SmaltAlign/cov_plot.R: /home/schmutz.stefan/miniconda3/envs/SmaltAlign/bin/Rscript: bad interpreter: No such file or directory

**Comment by sschmutz** [comment]
I removed the Rscript Shebang. Now you have to specify that you want to run that script with Rscript by yourself:
```
conda activate base
Rscript <path/to/SmaltAlign>/wts.R <path/to/files>
```
