### ISSUE TITLE
=-=-= lofreq with 0 cores =-=-=

### ISSUE THREAD

**Issue by Masterxilo** [medvir/SmaltAlign#7]
Hi there,

I am building a docker container for this pipeline. For testing, I am running it on a machine with just 1 core, but I have to remove this one line of smaltalign.sh: `cores=$(expr $cores / 2) ### only run on half the cores`

Because otherwise it outputs '=-=-= lofreq with 0 cores =-=-=' and produces a bunch of failures and division by 0 errors...

Can you change it so that if cores is 0 it at least sets it to 1? For example with another line:

cores="${cores/0/1}"

cheers
Paul

**Comment by MaryamZaheri** [comment]
Dear Paul, Thank you very much for your comment. It is modified in the coded.
